### ISSUE TITLE
remix-deno limitation

### ISSUE THREAD

**Issue by elycheikhsmail** [jacob-ebey/remix-deno-example#1]
Thank you @jacob-ebey for this remix-deno template, I think this is great step in right direction.
I know it us new template but I still have ask about what are the limitation of remix-deno compared to remix-node ?

**Comment by jacob-ebey** [comment]
Don't use this for production. This isn't a *real* Remix template and doesn't use the Remix compiler. If you are looking at using Remix + Deno, check out the official template, then the only limitations are Deno vs Node runtime ones.

This particular repo uses a custom, and super experimental runtime compiler that doesn't even support importing assets like CSS.

Feel free to hack on this, but again, this isn't anything official. I'll probably abandon this repo in a week when I'm bored of it or the ideas are picked up and implemented elsewhere.

**Comment by elycheikhsmail** [comment]
Thank you @jacob-ebey
